version: 2

sources:
 - name: adventureworksdw
   description: A clone of a Postgres database of Adventure Works operations.
   database: 
   schema: adventureworksdw
   tables:
     - name: sales_customer
       description: Raw customers data.
       columns:
         - name: customerid
           description: Primary key for customers.
           tests:
             - unique
             - not_null
         - name: personid
           description: Foreing Key for humanresources.person
           tests:
             - unique
             - not_null
     - name: production_product
       description: Raw products data.
       columns:  
         - name: productid
           description: Primary key for products.
           tests:
             - unique
             - not_null
         - name: productnumber 
           description: Unique product identification number
           tests:
             - unique
         - name: productsubcategoryid
           description: Foreing key for production.productsubcategory
           tests:
             - unique
         - name: productmodelid
           description: Foreing key for production.productmodel
           tests:
             - unique     
     - name: store
       description: Raw store data.
     - name: salesreason
       description: Raw salesreason data.
       columns:  
         - name: sales_reason_id
           description: Primary key for salesreason.
           tests:
             - unique
             - not_null
     - name: salesorderdetail
       decription: details of sales
       columns:
          - name: sales_order_detail_id
            description: primary key for salesorderdetail.
            tests:
             - unique
             - not_null
     - name: salesorderheadersalesreason
       description: reason of sales.
     - name: salesorderheader
       description: description of orders.
     - name: salesperson
       description: description of sales of persons.
     - name: salespersonquotahistory
       description: sales person quota history.
     - name: stateprovince
       description: states.
     - name: address
       description: addres of city.
     - name: employee
       decription: details from employees.
     - name: person
       decription: details from persons.
     - name: countryregion
       description: country regions.
     - name: creditcard
       description: Creditcard informations.
